version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=shinkansen.proxy.rlwy.net:35601
      - PMA_PORT=35601
      - PMA_USER=root
      - PMA_PASSWORD=QwEcmPIshDbiEBHESAbwpadkwvthuHAN